version: '3.4'

services:
  saldodb:
    image: mongo

  rediscache:
    image: redis

  transacaoapi:
    image: ${DOCKER_REGISTRY-}transacaoapi
    build:
      context: .
      dockerfile: Services/Saldo.TransacaoAPI/Dockerfile

  saldoapi:
    image: ${DOCKER_REGISTRY-}saldoapi
    build:
      context: .
      dockerfile: Services/Saldo.SaldoAPI/Dockerfile

volumes:
  mongo_data: